version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "npm"
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
      day: "friday"
